FROM golang:1.20 as build
WORKDIR /lambda

RUN apt-get update && apt-get install -y zip

COPY . ./
RUN go build -tags lambda.norpc -o bootstrap .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap -tags lambda.norpc .

ARG ZIPFILE=lambda.zip
RUN zip --quiet -9r /${ZIPFILE}  bootstrap

FROM scratch
ARG ZIPFILE
COPY --from=0 /${ZIPFILE} /

